spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://localhost:3306/msauth?createDatabaseIfNotExist=true
    username: root
    password: root12345
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
